language: python

python:
  - "3.9"

install:
  - pip install -r requirements.txt
  - pip install pytest-cov pytest
  - pip install codecov
  - pip install .

script:
  py.test  --cov-report term --cov=pconway

after_success:
  bash <(curl -s https://codecov.io/bash)
