language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
- pip install pytest-cov pytest
- pip install codecov
- pip install .
script: py.test  --cov-report term --cov=pconway
after_success: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pypi
  username: __token__
  password:
    secure: nWt3KiOopkr2TdZQyRTZwnG6oal/6n05M4zPLFb9CrLEDdbKyTYikiGExh5KjSK+y6aSS99rGNBChhauQXz1uMThweTtxvWBk+Q8FW/ezfY/pC8UeltggG4m33s8F2F4cPsPZnthC+pcpZgDTaVTHqfO5QYWTtRex6qvZkMY2xdofdKfbI8FBE2xJyrLdP3Y0PyuROYqHjCdEYKiQWwqDtzt/xZ+9K72tEqRpCIh/cGw/+oo2nz6uMtlkc+C0T9QconY5hBDtoCljvKtBMwWYHyjiq07YZrXkVbZYlTL+hzqv9iaV2MYhmEBkJokLgbRQyapGqPoJhTpUyizuh74O2x+Tap7HD+3/5/LbqQXxgeKI4YZIJF+2Hy2z/tnjhU4CvXfQzL/Wt0LKebhMKdcby309hOfh8WKxj8bPknZ9epGhANuRuYlHgKZY4tCahC1hjkNtWOBy46nogq6QIUcMlcIFP49KI8Y0Sasf+v+l3sMMm14qrxnRabrckv1U9CkX43spIVRmrZfOnk2La1ub0f4qOYZFnvLWTHajkeu8rqoH/LG/STLUJJXemGFvj9dxJjwndyR13Qu5HRbEQ9OFjNcDwIZ6yiLQJ3tNoFSW1w1tj7i6xAjZdzjAft0L40LnBgGhcpQ2BqplbW7wsdR5C9W5F1jdAEOigrnDd6mVqQ=
