language: python
python:
- '3.8'
install:
- pip install -r requirements.txt
- pip install pytest-cov pytest
- pip install codecov
- pip install .
script: py.test  --cov-report term --cov=pconway
after_success: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: pypi
  username: __token__
  password:
    secure: VVvRNs0ynmrpGad13PFQazT1bdNRVHYYfXNjuN2Kta9x3RkopJMCSZs39RRGbPL105BPTD8D7l7JWfmCJkKc8ntz6hQQw16D/exBE2Enzgej/njSkvQh6NdhlzT0m0DWe32EFXbrjb7jOhjSRxGZohBucvrYyWfaSi4p4MfYuoOw7+t8D2A3GH7msYVXbHjEQsY5wNq9T1Oqfpf8D+ves8teqi814kz4nNh4qMga6kCRL0M2wWNHt3utX4CllqsIIHQiINCtNb3lHVJ1OYtl/AqrGbZD4x08Bfv9knr90moWnoQW/a2kSBwrJpQ/w1qCi6hwfWglVxQsPwleUq06YCpOB5OumwQuDprofNERNjFqtwue6pS6xxylksXeK8QE8SJYTpVW+3UVQHHM4JtLMlkt/KffcCWgqLObaWglFXpX3mDEpLtwwZ9A0PU/Xd480DrxtrPSX0k6N79TGw08Q9YLP+pFXsK9ze/LDurngK/r7lpkD+uxe9rslX3RpJnv8dkaaSM0bTKqmAsvB1FPU8a5LRKtP0o8w1i4nPpbVRnQsL0YnGqyDI5r1KBol4VCXaxOQNmAawoigOr3u8SuEcM4dAavd7DpywVQ7Oc4RzWCr+8LfG6mRLkjMR85ukJWG0wY4Cd6r7JSbA9zghD9b3TbWBvj2tmYbzgo/gzVJx4=
  on:
    tags: true
